---
name: release

"on":
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Tagged Release
    runs-on: ubuntu-latest
    needs: integration
    if: github.tag

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "*"
